- hosts: localhost
  tasks:
  - name: package module to  install httpd
    package:
     name: "httpd"
     state: present

  - name: module to start httpd service
    service:
     name: "httpd"
     state:  started
     enabled: true


