- hosts: all
  tasks:
  - name: installing package
    package:
     name: "httpd"
     state: present

  - name: copying index.html to ansible target node
    copy:
      src: "index.html"
      dest: "/var/www/html"

  - name: starting httpd service
    service:
     name: "httpd"
     state:  started
     enabled: true

